--Импорт в таблицу Бар
INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Olive Oak', 'St. Louis');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Cherry Blossom PUB', 'Washington DC');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Farina', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Alembic', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('One Sixty Blue', 'Chicago, Ill');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Partender', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Osha', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Republic Street Bar', 'Fort Worth');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Bon Vivants', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Wingtip', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Blackbird', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Treo', 'New Orleans');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Pabu', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Fog Harbor Fish House', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Backbar', 'Somerville');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Blackbird', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Small Victory', 'Austin');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Usual', 'Fort Worth');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Treo', 'New Orleans');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Death Co.', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('NEAT', 'Westport');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Stookey''s Club Moderne', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('ABV', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Treo', 'New Orleans');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Urchin Bistrot', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Trick Dog', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Turnkey', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Burritt Tavern', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Tooker Alley', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Hotel Monteleone', 'New Orleans');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('NEAT', 'Westport');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Pabu', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Ziryab', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Devil''s Acre', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Mourad', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Death Co.', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Sailing Bar', 'Japan');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('BDK Restaurant Bar', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Forgery', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('GreenRiver', 'Chicago');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Bon March?', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Forgery', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Soigne Group', 'Los Angeles');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Eastern Standard', 'Boston');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Treasury', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Tony''s Pizza Napoletana', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Cherry Blossom PUB', 'Washington DC');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Must', 'Los Angeles');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Surfcomber', 'Miami');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Best Intentions', 'Chicago');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Mora Bar Kitchen', 'United Kingdom');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Cedars Social', 'Dallas');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Backbar', 'Somerville');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('ACME', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Forgery', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('PDT ', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Ration Dram', 'Atlanta');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Wildhawk', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Henri', 'Chicago');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Southside Spirit House', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Mister Jiu''s', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Juliet Ristorante', 'Austin');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Amor y Amargo', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Saxon Parole', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Comstock Saloon', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Union Lodge No.1', 'Denver');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Commissary', 'Los Angeles');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Michael Mina Restaurant Group', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Wish Bar', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Trou Normand', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('AMK Kitchen Bar', 'Chicago');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Small Victory', 'Austin');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Japonais', 'Chicago');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Best Intentions', 'Chicago');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Treasury', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Wildhawk', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Miles', 'Brooklyn');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Tippling Hall', 'Chicago');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Drago Centro', 'Los Angeles');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('White Oak Tavern', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Mizu Izakaya', 'Denver');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Pouring Ribbons', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Tin Roof Drink Community', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Forgery', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Departure', 'Denver');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Spare Room', 'Los Angeles');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Soigne Group', 'Los Angeles');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Michael Mina Restaurant Group', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Eastern Standard', 'Boston');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Artusi', 'Seattle');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Putnam''s Pub Cooker', 'Brooklyn');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Cocteleria', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Death Co.', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Edison', 'Los Angeles');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Burritt Room', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Ancestral Garden Bar Restaurant', 'New Zealand');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Soigne Group', 'Los Angeles');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Local Edition', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Eleven Madison Park', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Death Co.', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('A Japanese Kirikata', 'Spain');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('LARK on the Park', 'Dallas');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Caffe Dante', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Cherry Blossom PUB', 'Washington DC');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Fifth Floor', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Harper Rye', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Momofuku', 'Chicago');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Siena Tavern', 'Chicago');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Bar Siena', 'Chicago');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Mourad', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Padrecito', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Cala', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Pacific Cocktail Haven', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Jupiter Olympus', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Olde Bar', 'Philadelphia');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Arthur Ave.', 'Houston');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Biltong Bar', 'Atlanta');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Ida Claire', 'Dallas');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('La Mar Cebicheria Peruana', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Jupiter Olympus', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Expatriate', 'Portland');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('American Express Centurion Lounge', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Novo Restaurant Lounge', 'San Luis Obispo');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Matador', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Jupiter Olympus ', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Mourad', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Henrietta Red', 'Nashville');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Walter Foods', 'Brooklyn');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Death Co.', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Michael Mina Restaurant Group', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Tradition', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('House of Blues Anaheim', 'Anaheim');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Whitechapel', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Blackbird', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Park Tavern', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Biltong Bar', 'Atlanta');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Death Co.', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Bend Liquor Lounge', 'Miami');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Death Co.', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Drink', 'Boston');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Gin Room', 'St. Louis');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Trick Dog', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Backbar', 'Somerville');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Bonneville', 'Austin');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Treo', 'New Orleans');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Jupiter Olympus', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Maven', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Violet Hour', 'Chicago');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Treo', 'New Orleans');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Lolinda', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Novela', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Bryant''s Cocktail Lounge', 'Milwaukee');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Horsefeather', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Hog Island Oyster Co.', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('PDT', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Benjamin Cooper', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Rob Roy, The Hideout', 'Seattle');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Gin Joint', 'Charleston');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Savor Gastropub', 'Dallas');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Hawthorne', 'Boston');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Jupiter Olympus', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Forgery Verso', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Blackbird', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Hotel Monteleone', 'New Orleans');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Trick Dog', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Rickhouse', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Spitfire Bar', 'New Orleans');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Snake Oil Company', 'San Diego');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Imperial', 'Portland');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Rye', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Ziryab', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Skyfall Lounge', 'Las Vegas');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Union Lodge No.1', 'Denver');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('American Oak', 'Alameda');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('The Bywater', 'Los Gatos');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('ABV', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Shady Lady Saloon', 'Sacramento');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Bar Stella', 'Los Angeles');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Cocteleria', 'New York');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Rob Roy', 'Seattle');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('AQ', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Capo Restaurant', 'Boston');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Presidio Social Club', 'San Francisco');

INSERT INTO BAR (BAR_NAME, CITY_NAME) 
VALUES ('Bar Goto', 'New York');


--Импорт в таблицу Cocktail

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('#106 Cocktail');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('“Prepare for Destiny! Where’s my Pizza?”');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('10 to 7');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('A Bloody Shame');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('A Botanical Garden');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('A Regal Air ');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('A Southern Jackass');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('A Tall Tell');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('A.Nise');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Above My Pay Grade');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Amaretto Jello Shot, Why Not');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Amaretto Sour BV-Style');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('An Oaxacan Christmas');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Apples Grapes');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Baile de Verano');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Bakko Zengo');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Barrel Aged Ginger Negroni');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Basilway Daquiri');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Bianco Americano');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Bird On');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Bird to Buck');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Boko Buku');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Boomin'' Granny');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Brisa del Sur');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Buenaventura');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Buster Crusta');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Canary vs. the Coal Mine');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Cap''t of the Seven Seas');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Champs ?lys?es');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Chapman Cobbler');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Charente Royale');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Cherry Bark Martinez');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Cherry Orchard');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Chilcano (variation)');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Chingerito');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Classic Lolita');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Cocao Martini ');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Cock-tail');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Coffee Clove');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Conference');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Cove');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Creek Ran Dry');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Creole');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Croatia Firing Squad');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Cullerton Street');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Day For Night');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Delicious Sour');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Dirt Nap');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Doitashimashie');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Don''t Rock the Boat Punch');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Double Trouble');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Down the Rabbit Hole');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Eat, Drink and Be Cherry');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('El Mustavo');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Endless Summer');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Far From the Tree');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Farmer''s Gold');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Fiery Clydesdale');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Fizzy Rhubarb Mule');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Flight to Peru');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Floral Summer');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Fourth Generation');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('French Maid');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Full of Bologna');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Georgia Old Fashioned');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Gin Made Me Do It');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Goat Town Swizzle');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Gold Rush');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Happiness');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Heard It Through The Grapevine');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Heart Breaker');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Hibiscus Pisco Sour');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Hippi Hill');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Holland House');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Hotaling Old Tom Gin');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('I''m Only Happy when it Rains');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Im(pear)ed Fashioned');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Improved Calvados Cocktail');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('In HINEsight');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('IPA Mule');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Iron Fist in a Velvet Glove');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Jammie Dodger Fizz');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Japonais No.3');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Julia''s Child');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Junipero Jolly');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Just Beet It');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Kind of Fancy');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('King''s Mule');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('La Batida Loca');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('La La Land');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('La Maracuja');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Last Samurai');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Le Femme Nikita');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Little Ground Tapper');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Lonesome George');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Long Division');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Lox');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Lucky No.3');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Lux Japanese Lemonade');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Lux Shandy');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Luxardo Sour');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Mack''s Apple');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Mandrake');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Mango No. 3');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Match Grip Julep');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Mayahuel''s Revenge');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Mayan Mule');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Merry Sherry Cobbler');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Mexico Mule');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Motel Nacional');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Mother Superior');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Mott and Mulberry');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Muddled Mission');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Nara Mule');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Nectar of the Amazon');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Negroni Sorbetto');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Neko Colada');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Newton''s Theory');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Nick Janae');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Nigamono');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('No.10');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('No3');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Nori Islay');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Nuestra Julep');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Oaxacan Martini');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('OH Snap!');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('On the Fritz');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('On the Wings of Eagles');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Palermo Breeze');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Pants off Dance off');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Peachy Keane');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Peter Pumpkin');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Phineas Flip');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Piedra de sol');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Pineapple Express');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Polish Penance');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Potrero Hill');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Prickly Pear Margarita');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Prince of Humbugs');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Pumpkin Pecan');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Red Hook');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Rudolph''s Rose');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Rx Hot Toddy');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Sade''s Taboo');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Sage Sound');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Sahara Glowing Heart');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('San Fran Soda');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('San Francisco Harvest');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('San Francisco Strong (Skrong)');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Second City Sour');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Short Round II');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Sidecar');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Sidewinder');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Slow Ride');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Snow Bunny');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Solera Sidecar');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Space Age Pop');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Spanish GT');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Spring Forward');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Still Life of a Pineapple');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Strike No.3');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Stroll Through the Park');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Swedish Nightingale');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Tahitian Fix');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Temple of the Moon');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Tequila Sunflare');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The 42nd Round');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Bossa Nova');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Boys of Summer Cup');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Canevari Cocktail');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Chief');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Commissioner''s Trophy #3');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Double Crown');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Douglas Tilden');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Dry Cruise');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Fall 75');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The French Connection');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Great Pumpkin Cocktail');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Greatest Punch on Earth');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Happy Place');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The King''s Medicine');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Kings Mule');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Last Tango');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Lover''s Quarrel ');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Naughty Nice');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Nutty Sensation');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Palace Cellar');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Professor');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Stand By');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Swedish');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Thyme for Bed');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Under the Sun');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Union Jack');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Wabash Avenue Sour');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('West Bank');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Where''s the Orgeat?');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Willow');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Winter Season');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Wooster 53');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Xmas in Juniper');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Yes, Queen!');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('You Bet Your Ascot');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('You Go Glen Coco');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('You''re Bitter Than That');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Ypioca Yellow Card');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Yuzu Sazerac');

--Импорт в таблицу human

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Chelsea Little');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Paul Taylor');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Gabriele Modica');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Danny Louie');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Amy Lewis ');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Julian Miller');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Kate KaiKaew');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Monica Anderson');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Scott Baird');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brandon Bigalke');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Matt Grippo');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Tyler Chauvin');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Nick Jones');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Nusan Brounstein');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Sam Treadway');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Matt Grippo');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Kelly O''Hare');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Tiki Dave ');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Tyler Chauvin');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jillian Vose');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Johel Huaman Barbosa  Christian Hurtado');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Matt Solario');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Ryan Fitzgerald');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Tyler Chauvin');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Rafael Jimenez Rivera');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Caitlin Laman');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Kevin Diedrich');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Josh Trabulsi');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Del Prado');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Marvin Allen');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Johel Huaman Barbosa Christian Hurtado');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Nick Jones');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Zachary Brian Taylor');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Keli Rivers');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Anthony Parks');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Miller');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Takumi  Watanabe');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Kevin Diedrich');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Ken Luciano');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Julia Momose');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Eric Quilty');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Ken Luciano');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Nick Meyer');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Kevin Martin');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Ryan Hall');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Elmer Mejicano');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Paul Taylor');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Coly Den');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Chad Philips');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Calvin Marty');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Lucia Stucki');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Tom Cavazos');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Sam Treadway');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Duane Fernandez');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Ken Luciano');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jim Meehan');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Andy Minchow');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Karri Cormican');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Clint Rogers');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Leilani Brennan');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Danny Louie');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jeramy Campbell');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Sother Teague');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Naren Young');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Karri Cormican');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jason Patz');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Enrique Sanchez');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Carlo Splendorini ');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Ashley Wacker');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Thad Vogler');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jon Ruiz');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Laura Maddox');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Bruce Cole');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Calvin Marty');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Carlos Yturria');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Sarah Ruiz');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jacques');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Daniel Romero');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Paul Sauter');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jaymee Mandeville');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Luis Hernandez');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Nate Matson');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Joaquin Simo');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Claire Chad');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jacques');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brandon Weiss');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Karen Grill');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Nick Meyer');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Carlo Splendorini');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Naomi Levy');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Adam Fortuna');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Mariel Bordas');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Diego Sanchez');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jarred Weigand');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('BC Hoffman');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Josh Trabulsi');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Benedict Simpson');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Nick Meyer');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Alex Quesada');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Leo Robitschek');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Joaquin Simo');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Eduardo Val Naval');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Matt Orth');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Hung Nguyen');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Paul Taylor');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('David Ruiz');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('John deBarry ');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Revae Schneider');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Revae Schneider');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Anthony Parks');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('David Ruiz');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Gina Scheurte');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Kevin Diedrich');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Eric Quilty');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Matthew Polzin');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Lainey Collum');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Sean Gleason');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Bonnie Wilson');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('John Weyrich');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Morgan Schick');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Graham Hunter Gregg');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jim Meehan');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Theo Sabatini');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Edgar Joselino Solis');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Morgan Schick ');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Collin Nicholas');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Patrick Halloran');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Christopher Buono');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jessica Gonzalez');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('John Codd');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Devin Hardy');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Megan Daniel');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Matt Grippo');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Patrick Poelvoorde');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Sean Gleason');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Phil Ward');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Sam Wiener');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Joaquin Simo');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Misty Kalkofen');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Natasha Bahrami');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Kim Rosselle');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Daniel Braganca');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jennifer Costello');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Tyler Chauvin');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Morgan Schick');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Kate Bolton');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Nandini Khaund');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Tyler Chauvin');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Raul Ayala');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Chris Lane');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Alex Smith');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jeff Kinder');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Ian Scalzo');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Saul Ranella');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jeff Bell');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Mo Hodges Brian Felley');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jacyara de Oliveira');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Nicole Hassoun');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('John Davis');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jackson Cannon');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Morgan Schick');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Elizabeth Montana');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Matt Grippo');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Marvin Allen');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Kim Rosselle');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Russell Davis');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Sarah Manowitz');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Raul Ayala');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Michael Esposito');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brandon Wise');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Vince Toscano');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Zachary Brian Taylor');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Lisa Brier');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Brian Means');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jason Patz');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Phillip Ricafort');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Claire Sprouse');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jackie Goldstein');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Carl Wenger');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Michael Blum');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Diego Sanchez');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Raul Ayala');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jacyara de Oliveira');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Jason Rager');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Crystal Chasse');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Kevin Mabry');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Scott Brody');

INSERT INTO HUMAN (HUMAN_NAME) 
VALUES ('Kenta Goto');

--импорт в таблицу humanbar

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Chelsea Little', 'Olive Oak');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Paul Taylor', 'Cherry Blossom PUB');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Gabriele Modica', 'Farina');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Danny Louie', 'Alembic');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Amy Lewis ', 'One Sixty Blue');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Julian Miller', 'Partender');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Kate KaiKaew', 'Osha');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Monica Anderson', 'Republic Street Bar');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Scott Baird', 'The Bon Vivants');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brandon Bigalke', 'Wingtip');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Matt Grippo', 'Blackbird');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Tyler Chauvin', 'Treo');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Nick Jones', 'Pabu');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Nusan Brounstein', 'Fog Harbor Fish House');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Sam Treadway', 'Backbar');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Matt Grippo', 'Blackbird');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Kelly O''Hare', 'Small Victory');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Tiki Dave ', 'The Usual');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Tyler Chauvin', 'Treo');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jillian Vose', 'Death Co.');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Johel Huaman Barbosa  Christian Hurtado', 'NEAT');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Matt Solario', 'Stookey''s Club Moderne');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Ryan Fitzgerald', 'ABV');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Tyler Chauvin', 'Treo');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Rafael Jimenez Rivera', 'Urchin Bistrot');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Caitlin Laman', 'Trick Dog');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Kevin Diedrich', 'Turnkey');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Josh Trabulsi', 'Burritt Tavern');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Del Prado', 'Tooker Alley');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Marvin Allen', 'Hotel Monteleone');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Johel Huaman Barbosa Christian Hurtado', 'NEAT');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Nick Jones', 'Pabu');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Zachary Brian Taylor', 'Ziryab');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Keli Rivers', 'The Devil''s Acre');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Anthony Parks', 'Mourad');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Miller', 'Death Co.');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Takumi  Watanabe', 'The Sailing Bar');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Kevin Diedrich', 'BDK Restaurant Bar');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Ken Luciano', 'The Forgery');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Julia Momose', 'GreenRiver');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Eric Quilty', 'Bon March?');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Ken Luciano', 'The Forgery');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Nick Meyer', 'The Soigne Group');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Kevin Martin', 'Eastern Standard');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Ryan Hall', 'The Treasury');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Elmer Mejicano', 'Tony''s Pizza Napoletana');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Paul Taylor', 'Cherry Blossom PUB');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Coly Den', 'The Must');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Chad Philips', 'Surfcomber');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Calvin Marty', 'Best Intentions');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Lucia Stucki', 'Mora Bar Kitchen');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Tom Cavazos', 'The Cedars Social');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Sam Treadway', 'Backbar');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Duane Fernandez', 'ACME');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Ken Luciano', 'The Forgery');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jim Meehan', 'PDT ');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Andy Minchow', 'Ration Dram');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Karri Cormican', 'Wildhawk');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Clint Rogers', 'Henri');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Leilani Brennan', 'Southside Spirit House');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Danny Louie', 'Mister Jiu''s');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jeramy Campbell', 'Juliet Ristorante');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Sother Teague', 'Amor y Amargo');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Naren Young', 'Saxon Parole');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Karri Cormican', 'Comstock Saloon');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jason Patz', 'Union Lodge No.1');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Enrique Sanchez', 'The Commissary');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Carlo Splendorini ', 'Michael Mina Restaurant Group');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Ashley Wacker', 'Wish Bar');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Thad Vogler', 'Trou Normand');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jon Ruiz', 'AMK Kitchen Bar');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Laura Maddox', 'Small Victory');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Bruce Cole', 'Japonais');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Calvin Marty', 'Best Intentions');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Carlos Yturria', 'The Treasury');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Sarah Ruiz', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jacques', 'Wildhawk');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Daniel Romero', 'Miles');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Paul Sauter', 'Tippling Hall');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jaymee Mandeville', 'Drago Centro');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Luis Hernandez', 'White Oak Tavern');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Nate Matson', 'Mizu Izakaya');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Joaquin Simo', 'Pouring Ribbons');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Claire Chad', 'Tin Roof Drink Community');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jacques', 'The Forgery');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brandon Weiss', 'Departure');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Karen Grill', 'The Spare Room');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Nick Meyer', 'The Soigne Group');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Carlo Splendorini', 'Michael Mina Restaurant Group');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Naomi Levy', 'Eastern Standard');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Adam Fortuna', 'Artusi');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Mariel Bordas', 'Putnam''s Pub Cooker');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Diego Sanchez', 'Cocteleria');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jarred Weigand', 'Death Co.');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('BC Hoffman', 'The Edison');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Josh Trabulsi', 'Burritt Room');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Benedict Simpson', 'Ancestral Garden Bar Restaurant');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Nick Meyer', 'The Soigne Group');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Alex Quesada', 'Local Edition');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Leo Robitschek', 'Eleven Madison Park');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Joaquin Simo', 'Death Co.');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Eduardo Val Naval', 'A Japanese Kirikata');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Matt Orth', 'LARK on the Park');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Hung Nguyen', 'Caffe Dante');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Paul Taylor', 'Cherry Blossom PUB');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Fifth Floor');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('David Ruiz', 'Harper Rye');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('John deBarry ', 'Momofuku');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Revae Schneider', 'Siena Tavern');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Revae Schneider', 'Bar Siena');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Anthony Parks', 'Mourad');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('David Ruiz', 'Padrecito');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Gina Scheurte', 'Cala');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Kevin Diedrich', 'Pacific Cocktail Haven');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Eric Quilty', 'Jupiter Olympus');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Matthew Polzin', 'The Olde Bar');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Lainey Collum', 'Arthur Ave.');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Sean Gleason', 'Biltong Bar');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Bonnie Wilson', 'Ida Claire');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('John Weyrich', 'La Mar Cebicheria Peruana');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Morgan Schick', 'Jupiter Olympus');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Graham Hunter Gregg', 'Expatriate');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jim Meehan', 'American Express Centurion Lounge');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Theo Sabatini', 'Novo Restaurant Lounge');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Edgar Joselino Solis', 'Matador');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Morgan Schick ', 'Jupiter Olympus ');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Collin Nicholas', 'Mourad');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Patrick Halloran', 'Henrietta Red');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Christopher Buono', 'Walter Foods');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jessica Gonzalez', 'Death Co.');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Michael Mina Restaurant Group');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('John Codd', 'Tradition');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Devin Hardy', 'House of Blues Anaheim');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Megan Daniel', 'Whitechapel');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Matt Grippo', 'Blackbird');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Patrick Poelvoorde', 'Park Tavern');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Sean Gleason', 'Biltong Bar');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Phil Ward', 'Death Co.');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Sam Wiener', 'The Bend Liquor Lounge');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Joaquin Simo', 'Death Co.');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Misty Kalkofen', 'Drink');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Natasha Bahrami', 'The Gin Room');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Kim Rosselle', 'Trick Dog');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Daniel Braganca', 'Backbar');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jennifer Costello', 'Bonneville');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Tyler Chauvin', 'Treo');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Morgan Schick', 'Jupiter Olympus');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Kate Bolton', 'Maven');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Nandini Khaund', 'The Violet Hour');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Tyler Chauvin', 'Treo');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Raul Ayala', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Chris Lane', 'Lolinda');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Alex Smith', 'Novela');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jeff Kinder', 'Bryant''s Cocktail Lounge');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Ian Scalzo', 'Horsefeather');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Saul Ranella', 'Hog Island Oyster Co.');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jeff Bell', 'PDT');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Mo Hodges Brian Felley', 'Benjamin Cooper');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jacyara de Oliveira', 'Rob Roy, The Hideout');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Nicole Hassoun', 'The Gin Joint');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('John Davis', 'Savor Gastropub');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jackson Cannon', 'The Hawthorne');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Morgan Schick', 'Jupiter Olympus');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Elizabeth Montana', 'Forgery Verso');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Matt Grippo', 'Blackbird');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Marvin Allen', 'Hotel Monteleone');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Kim Rosselle', 'Trick Dog');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Russell Davis', 'Rickhouse');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Sarah Manowitz', 'Spitfire Bar');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Raul Ayala', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Michael Esposito', 'Snake Oil Company');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brandon Wise', 'Imperial');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Vince Toscano', 'Rye');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Zachary Brian Taylor', 'Ziryab');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Lisa Brier', 'Skyfall Lounge');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Brian Means', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jason Patz', 'Union Lodge No.1');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Phillip Ricafort', 'American Oak');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Claire Sprouse', 'The Bywater');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jackie Goldstein', 'ABV');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Carl Wenger', 'Shady Lady Saloon');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Michael Blum', 'Bar Stella');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Diego Sanchez', 'Cocteleria');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Raul Ayala', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jacyara de Oliveira', 'Rob Roy');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Jason Rager', 'AQ');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Crystal Chasse', 'Dirty Habit');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Kevin Mabry', 'Capo Restaurant');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Scott Brody', 'Presidio Social Club');

INSERT INTO HUMANBAR (HUMAN_NAME, BAR_NAME) 
VALUES ('Kenta Goto', 'Bar Goto');

--импорт в таблицу humancocktail

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('#106 Cocktail', 'Chelsea Little');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('“Prepare for Destiny! Where’s my Pizza?”', 'Paul Taylor');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('10 to 7', 'Gabriele Modica');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('A Bloody Shame', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('A Botanical Garden', 'Danny Louie');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('A Regal Air ', 'Amy Lewis ');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('A Southern Jackass', 'Julian Miller');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('A Tall Tell', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('A.Nise', 'Kate KaiKaew');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Above My Pay Grade', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Amaretto Jello Shot, Why Not', 'Monica Anderson');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Amaretto Sour BV-Style', 'Scott Baird');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('An Oaxacan Christmas', 'Brandon Bigalke');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Apples Grapes', 'Matt Grippo');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Baile de Verano', 'Tyler Chauvin');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Bakko Zengo', 'Nick Jones');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Barrel Aged Ginger Negroni', 'Nusan Brounstein');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Basilway Daquiri', 'Sam Treadway');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Bianco Americano', 'Matt Grippo');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Bird On', 'Kelly O''Hare');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Bird to Buck', 'Tiki Dave ');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Boko Buku', 'Tyler Chauvin');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Boomin'' Granny', 'Jillian Vose');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Brisa del Sur', 'Johel Huaman Barbosa  Christian Hurtado');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Buenaventura', 'Matt Solario');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Buster Crusta', 'Ryan Fitzgerald');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Canary vs. the Coal Mine', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Cap''t of the Seven Seas', 'Tyler Chauvin');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Champs ?lys?es', 'Rafael Jimenez Rivera');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Chapman Cobbler', 'Caitlin Laman');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Charente Royale', 'Kevin Diedrich');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Cherry Bark Martinez', 'Josh Trabulsi');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Cherry Orchard', 'Del Prado');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Chilcano (variation)', 'Marvin Allen');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Chingerito', 'Johel Huaman Barbosa Christian Hurtado');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Classic Lolita', 'Nick Jones');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Cocao Martini ', 'Zachary Brian Taylor');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Cock-tail', 'Keli Rivers');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Coffee Clove', 'Anthony Parks');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Conference', 'Brian Miller');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Cove', 'Takumi  Watanabe');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Creek Ran Dry', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Creole', 'Kevin Diedrich');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Croatia Firing Squad', 'Ken Luciano');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Cullerton Street', 'Julia Momose');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Day For Night', 'Eric Quilty');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Delicious Sour', 'Ken Luciano');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Dirt Nap', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Doitashimashie', 'Nick Meyer');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Don''t Rock the Boat Punch', 'Kevin Martin');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Double Trouble', 'Ryan Hall');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Down the Rabbit Hole', 'Elmer Mejicano');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Eat, Drink and Be Cherry', 'Paul Taylor');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('El Mustavo', 'Coly Den');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Endless Summer', 'Chad Philips');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Far From the Tree', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Farmer''s Gold', 'Calvin Marty');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Fiery Clydesdale', 'Lucia Stucki');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Fizzy Rhubarb Mule', 'Tom Cavazos');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Flight to Peru', 'Sam Treadway');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Floral Summer', 'Duane Fernandez');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Fourth Generation', 'Ken Luciano');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('French Maid', 'Jim Meehan');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Full of Bologna', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Georgia Old Fashioned', 'Andy Minchow');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Gin Made Me Do It', 'Karri Cormican');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Goat Town Swizzle', 'Clint Rogers');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Gold Rush', 'Leilani Brennan');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Happiness', 'Danny Louie');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Heard It Through The Grapevine', 'Jeramy Campbell');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Heart Breaker', 'Sother Teague');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Hibiscus Pisco Sour', 'Naren Young');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Hippi Hill', 'Karri Cormican');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Holland House', 'Jason Patz');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Hotaling Old Tom Gin', 'Enrique Sanchez');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('I''m Only Happy when it Rains', 'Carlo Splendorini ');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Im(pear)ed Fashioned', 'Ashley Wacker');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Improved Calvados Cocktail', 'Thad Vogler');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('In HINEsight', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('IPA Mule', 'Jon Ruiz');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Iron Fist in a Velvet Glove', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Jammie Dodger Fizz', 'Laura Maddox');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Japonais No.3', 'Bruce Cole');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Julia''s Child', 'Calvin Marty');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Junipero Jolly', 'Carlos Yturria');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Just Beet It', 'Sarah Ruiz');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Kind of Fancy', 'Jacques');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('King''s Mule', 'Daniel Romero');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('La Batida Loca', 'Paul Sauter');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('La La Land', 'Jaymee Mandeville');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('La Maracuja', 'Luis Hernandez');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Last Samurai', 'Nate Matson');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Le Femme Nikita', 'Joaquin Simo');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Little Ground Tapper', 'Claire Chad');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Lonesome George', 'Jacques');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Long Division', 'Brandon Weiss');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Lox', 'Karen Grill');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Lucky No.3', 'Nick Meyer');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Lux Japanese Lemonade', 'Carlo Splendorini');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Lux Shandy', 'Naomi Levy');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Luxardo Sour', 'Adam Fortuna');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Mack''s Apple', 'Mariel Bordas');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Mandrake', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Mango No. 3', 'Diego Sanchez');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Match Grip Julep', 'Jarred Weigand');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Mayahuel''s Revenge', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Mayan Mule', 'BC Hoffman');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Merry Sherry Cobbler', 'Josh Trabulsi');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Mexico Mule', 'Benedict Simpson');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Motel Nacional', 'Nick Meyer');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Mother Superior', 'Alex Quesada');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Mott and Mulberry', 'Leo Robitschek');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Muddled Mission', 'Joaquin Simo');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Nara Mule', 'Eduardo Val Naval');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Nectar of the Amazon', 'Matt Orth');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Negroni Sorbetto', 'Hung Nguyen');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Neko Colada', 'Paul Taylor');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Newton''s Theory', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Nick Janae', 'David Ruiz');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Nigamono', 'John deBarry ');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('No.10', 'Revae Schneider');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('No3', 'Revae Schneider');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Nori Islay', 'Anthony Parks');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Nuestra Julep', 'David Ruiz');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Oaxacan Martini', 'Gina Scheurte');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('OH Snap!', 'Kevin Diedrich');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('On the Fritz', 'Eric Quilty');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('On the Wings of Eagles', 'Matthew Polzin');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Palermo Breeze', 'Lainey Collum');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Pants off Dance off', 'Sean Gleason');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Peachy Keane', 'Bonnie Wilson');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Peter Pumpkin', 'John Weyrich');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Phineas Flip', 'Morgan Schick');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Piedra de sol', 'Graham Hunter Gregg');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Pineapple Express', 'Jim Meehan');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Polish Penance', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Potrero Hill', 'Theo Sabatini');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Prickly Pear Margarita', 'Edgar Joselino Solis');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Prince of Humbugs', 'Morgan Schick ');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Pumpkin Pecan', 'Collin Nicholas');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Red Hook', 'Patrick Halloran');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Rudolph''s Rose', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Rx Hot Toddy', 'Christopher Buono');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Sade''s Taboo', 'Jessica Gonzalez');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Sage Sound', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Sahara Glowing Heart', 'John Codd');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('San Fran Soda', 'Devin Hardy');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('San Francisco Harvest', 'Megan Daniel');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('San Francisco Strong (Skrong)', 'Matt Grippo');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Second City Sour', 'Patrick Poelvoorde');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Short Round II', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Sidecar', 'Sean Gleason');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Sidewinder', 'Phil Ward');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Slow Ride', 'Sam Wiener');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Snow Bunny', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Solera Sidecar', 'Joaquin Simo');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Space Age Pop', 'Misty Kalkofen');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Spanish GT', 'Natasha Bahrami');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Spring Forward', 'Kim Rosselle');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Still Life of a Pineapple', 'Daniel Braganca');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Strike No.3', 'Jennifer Costello');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Stroll Through the Park', 'Tyler Chauvin');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Swedish Nightingale', 'Morgan Schick');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Tahitian Fix', 'Kate Bolton');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Temple of the Moon', 'Nandini Khaund');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Tequila Sunflare', 'Tyler Chauvin');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The 42nd Round', 'Raul Ayala');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Bossa Nova', 'Chris Lane');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Boys of Summer Cup', 'Alex Smith');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Canevari Cocktail', 'Jeff Kinder');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Chief', 'Ian Scalzo');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Commissioner''s Trophy #3', 'Saul Ranella');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Double Crown', 'Jeff Bell');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Douglas Tilden', 'Mo Hodges Brian Felley');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Dry Cruise', 'Jacyara de Oliveira');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Fall 75', 'Nicole Hassoun');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The French Connection', 'John Davis');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Great Pumpkin Cocktail', 'Jackson Cannon');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Greatest Punch on Earth', 'Morgan Schick');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Happy Place', 'Elizabeth Montana');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The King''s Medicine', 'Matt Grippo');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Kings Mule', 'Marvin Allen');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Last Tango', 'Kim Rosselle');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Lover''s Quarrel ', 'Russell Davis');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Naughty Nice', 'Sarah Manowitz');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Nutty Sensation', 'Raul Ayala');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Palace Cellar', 'Michael Esposito');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Professor', 'Brandon Wise');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Stand By', 'Vince Toscano');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('The Swedish', 'Zachary Brian Taylor');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Thyme for Bed', 'Lisa Brier');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Under the Sun', 'Brian Means');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Union Jack', 'Jason Patz');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Wabash Avenue Sour', 'Phillip Ricafort');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('West Bank', 'Claire Sprouse');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Where''s the Orgeat?', 'Jackie Goldstein');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Willow', 'Carl Wenger');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Winter Season', 'Michael Blum');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Wooster 53', 'Diego Sanchez');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Xmas in Juniper', 'Raul Ayala');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Yes, Queen!', 'Jacyara de Oliveira');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('You Bet Your Ascot', 'Jason Rager');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('You Go Glen Coco', 'Crystal Chasse');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('You''re Bitter Than That', 'Kevin Mabry');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Ypioca Yellow Card', 'Scott Brody');

INSERT INTO HUMANCOCKTAIL (COCKTAIL_NAME, HUMAN_NAME) 
VALUES ('Yuzu Sazerac', 'Kenta Goto');

--импорт в таблицу City


INSERT INTO CITY (CITY_NAME) 
VALUES ('St. Louis');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Washington DC');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Chicago, Ill');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Fort Worth');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New Orleans');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Somerville');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Austin');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Fort Worth');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New Orleans');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Westport');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New Orleans');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New Orleans');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Westport');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Japan');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Chicago');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Los Angeles');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Boston');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Washington DC');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Los Angeles');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Miami');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Chicago');

INSERT INTO CITY (CITY_NAME) 
VALUES ('United Kingdom');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Dallas');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Somerville');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Atlanta');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Chicago');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Austin');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Denver');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Los Angeles');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Chicago');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Austin');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Chicago');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Chicago');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Brooklyn');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Chicago');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Los Angeles');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Denver');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Denver');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Los Angeles');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Los Angeles');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Boston');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Seattle');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Brooklyn');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Los Angeles');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New Zealand');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Los Angeles');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Spain');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Dallas');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Washington DC');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Chicago');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Chicago');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Chicago');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Philadelphia');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Houston');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Atlanta');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Dallas');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Portland');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Luis Obispo');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Nashville');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Brooklyn');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Anaheim');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Atlanta');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Miami');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Boston');

INSERT INTO CITY (CITY_NAME) 
VALUES ('St. Louis');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Somerville');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Austin');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New Orleans');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Chicago');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New Orleans');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Milwaukee');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Seattle');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Charleston');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Dallas');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Boston');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New Orleans');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New Orleans');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Diego');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Portland');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Las Vegas');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Denver');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Alameda');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Los Gatos');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Sacramento');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Los Angeles');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Seattle');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('Boston');

INSERT INTO CITY (CITY_NAME) 
VALUES ('San Francisco');

INSERT INTO CITY (CITY_NAME) 
VALUES ('New York');


