INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Flor de Amaras');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Happy Place');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Bon Voyage Pisco Punch');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Still Life of a Pineapple');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Bittered Valley');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('OH Snap!');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Wabash Avenue Sour');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('IPA Mule');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Ritz Cocktail');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('King''s Snap the Chocolate Out of You');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Happiness');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Fourth Generation');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('West Coast Punch');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Mille Miglia');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Paradiso Sun');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Lux Orchard Lemonade');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Cut & Rum');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The King''s Spring Daisy');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The King''s Ginger Spiced Punch');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('War of the Roses');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The King''s Medicine');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('A.Nise');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Down the Rabbit Hole');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Peace Daiquiri');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The King''s Autumn Cobbler');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Mad King');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Robert Baratheon');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Lux Shandy');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Fiona Graham');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Le Sang et Sable');








INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Backbar', 'Somerville');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Pacific Cocktail Haven', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('American Oak', 'Alameda');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('AMK Kitchen Bar', 'Chicago');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Mister Jiu''s', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('The Forgery', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Blackbird', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Osha', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Tony''s Pizza Napoletana', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Eastern Standard', 'Boston');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('The Bon Vivants', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Best Intentions', 'Chicago');


INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Padrecito', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Tippling Hall', 'Chicago');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Harper & Rye', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('The Olde Bar', 'Philadelphia');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Walter Foods', 'Brooklyn');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('The Gin Room', 'St. Louis');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('PDT ', 'New York');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Wildhawk', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Presidio Social Club', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Hotel Monteleone', 'New Orleans');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Tin Roof Drink Community', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Jupiter Olympus ', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Juliet Ristorante', 'Austin');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Local Edition', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('The Cedars Social', 'Dallas');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Turnkey', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Snake Oil Company', 'San Diego');







INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Kelly McCarthy');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Elizabeth Montana');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Jon Morales');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Daniel Braganca');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Nik Virrey');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Kevin Diedrich');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Phillip Ricafort');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Jon Ruiz');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Dale DeGroff');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Ian Julian');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Danny Louie');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Ken Luciano');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Caterina Miltenberger');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Caterina Miltenberger');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Caterina Miltenberger');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Caterina Miltenberger');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Jose Pereiro');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Kevin Diedrich');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Matt Grippo');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Kate KaiKaew');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Elmer Mejicano');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Kate Grutman');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Naomi Levy');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Chris Morris');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Toby Cecchini');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Scott Baird');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Calvin Marty');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Luis Hernandez');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Matt Grippo');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Laurent');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Tyler Chauvin');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Francesco Lafranconi');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Loris Melis');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Lauren Sanchez');








INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Kelly McCarthy');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Forgery & Verso', 'Elizabeth Montana');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Jon Morales');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Backbar', 'Daniel Braganca');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Nik Virrey');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Pacific Cocktail Haven', 'Kevin Diedrich');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('American Oak', 'Phillip Ricafort');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('AMK Kitchen Bar', 'Jon Ruiz');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Dale DeGroff');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Ian Julian');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Mister Jiu''s', 'Danny Louie');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('The Forgery', 'Ken Luciano');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Caterina Miltenberger');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Caterina Miltenberger');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Caterina Miltenberger');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Caterina Miltenberger');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Drift Fish House & Oyster Bar', 'Jose Pereiro');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, NULL);

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, NULL);

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Kevin Diedrich');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Blackbird', 'Matt Grippo');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Osha', 'Kate KaiKaew');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Tony''s Pizza Napoletana', 'Elmer Mejicano');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Kate Grutman');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, NULL);

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, NULL);

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, NULL);

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Eastern Standard', 'Naomi Levy');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Chris Morris');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Toby Cecchini');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, NULL);

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('The Bon Vivants', 'Scott Baird');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Best Intentions', 'Calvin Marty');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, NULL);

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('White Oak Tavern', 'Luis Hernandez');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Blackbird', 'Matt Grippo');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Padrecito', 'David Ruiz');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Tippling Hall', 'Paul Sauter');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES (NULL, 'Jay Zimmerman');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Harper & Rye', 'David Ruiz');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('The Olde Bar', 'Matthew Polzin');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Walter Foods', 'Christopher Buono');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('The Gin Room', 'Natasha Bahrami');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('PDT ', 'Jim Meehan');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Dirty Habit', 'Brian Means');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Dirty Habit', 'Brian Means');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Bon Vivants', 'Morgan Schick');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Dirty Habit', 'Brian Means');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Wildhawk', 'Karri Cormican');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Presidio Social Club', 'Scott Brody');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Bon Vivants', 'Morgan Schick');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('The Forgery', 'Ken Luciano');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Hotel Monteleone', 'Marvin Allen');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Tin Roof Drink Community', 'Claire & Chad');

INSERT INTO BARBARTENDER (BAR_NAME, BAR_NAME) 
VALUES ('Jupiter Olympus ', 'Morgan Schick ');
