INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Flor de Amaras');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Happy Place');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Bon Voyage Pisco Punch');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Still Life of a Pineapple');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Bittered Valley');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('OH Snap!');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Wabash Avenue Sour');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('IPA Mule');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Ritz Cocktail');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('King''s Snap the Chocolate Out of You');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Happiness');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Fourth Generation');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('West Coast Punch');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Mille Miglia');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Paradiso Sun');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Lux Orchard Lemonade');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Cut & Rum');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The King''s Spring Daisy');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The King''s Ginger Spiced Punch');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('War of the Roses');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The King''s Medicine');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('A.Nise');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Down the Rabbit Hole');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Peace Daiquiri');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The King''s Autumn Cobbler');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Mad King');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('The Robert Baratheon');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Lux Shandy');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Fiona Graham');

INSERT INTO COCKTAIL (COCKTAIL_NAME) 
VALUES ('Le Sang et Sable');






INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Forgery & Verso', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Backbar', 'Somerville');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Pacific Cocktail Haven', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('American Oak', 'Alameda');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('AMK Kitchen Bar', 'Chicago');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Mister Jiu''s', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('The Forgery', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Drift Fish House & Oyster Bar', 'Atlanta');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Blackbird', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Osha', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Tony''s Pizza Napoletana', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Eastern Standard', 'Boston');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('The Bon Vivants', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Best Intentions', 'Chicago');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('White Oak Tavern', 'New York');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Blackbird', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Padrecito', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Tippling Hall', 'Chicago');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Harper & Rye', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('The Olde Bar', 'Philadelphia');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Walter Foods', 'Brooklyn');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('The Gin Room', 'St. Louis');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('PDT ', 'New York');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Wildhawk', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Dirty Habit', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('Presidio Social Club', 'San Francisco');

INSERT INTO BAR (BAR_NAME, LOCATION) 
VALUES ('The Forgery', 'San Francisco');




INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Kelly McCarthy');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Elizabeth Montana');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Jon Morales');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Daniel Braganca');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Nik Virrey');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Kevin Diedrich');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Phillip Ricafort');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Jon Ruiz');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Dale DeGroff');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Ian Julian');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Danny Louie');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Ken Luciano');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Caterina Miltenberger');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Caterina Miltenberger');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Caterina Miltenberger');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Caterina Miltenberger');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Jose Pereiro');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Kevin Diedrich');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Matt Grippo');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Kate KaiKaew');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Elmer Mejicano');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Kate Grutman');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Naomi Levy');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Chris Morris');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Toby Cecchini');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Scott Baird');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Calvin Marty');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Luis Hernandez');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('Matt Grippo');

INSERT INTO BARTENDER (BARTENDER_NAME) 
VALUES ('David Ruiz');
